Note_port/notes/core/urls.py
from django.urls import path 
from . import views 
from django.contrib.auth import views as auth_views 
from . forms import LoginForm 

app_name = 'core'

urlpatterns = [
    path('', views.index, name= 'index'),
    path('signup/', views.signup, name= 'signup'),
    path('login/', auth_views.LoginView.as_view(template_name = 'templates/auth/login.html', authentication_form = LoginForm), name= 'login'),
    path('logout/', views.logout_user, name= 'logout'),
    path('profile/', views.profile, name= 'profile'),

]

Note_port/notes/items/urls.py
from django.urls import path 
from . import views

app_name = 'items'

urlpatterns = [
    path('mynotes/', views.view_notes, name= 'user_notes'),
    path('create/', views.new_notes, name= 'create'),
    path('mynotes/<int:id>/', views.notes_details, name= 'details'),
    
]

Note_port/notes/notes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'),),
    path('', include('items.urls'),),
    
]

Note_port/notes/core/models.py
from django.db import models

# Create your models here.

Note_port/notes/items/models.py
from django.db import models
from django.contrib.auth.models import User 

class Notes(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    title = models.CharField(max_length = 200)
    content = models.TextField()

    class Meta:
        verbose_name_plural = 'Notes'
        

Note_port/notes/core/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm 
from django.contrib.auth.models import User 

class SignupForm(UserCreationForm):
    class Meta:
        model = User 
        fields = ('username', 'email', 'password1', 'password2')

class LoginForm(AuthenticationForm):
    class Meta:
        model = User 
        fields = ('username', 'password')

Note_port/notes/items/forms.py
from django import forms 
from .models import Notes 

class new_note(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(new_note, self).__init__(*args, **kwargs)
        
        if user:
            self.fields['user'].initial = user
            
    class Meta: 
        model = Notes 
        fields = ('title', 'content' )

Note_port/notes/core/views.py
from django.shortcuts import render, redirect
from . forms import SignupForm  
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required 

def index(request):
    return render(request, 'templates/core/index.html')

def signup(request):
    if request.method == 'POST':
        signupform = SignupForm(request.POST)

        if signupform.is_valid():
            user = signupform.save()
            login(request, user)
            return redirect('/')
        
    signupform = SignupForm()
    return render(request, 'templates/auth/signup.html', {
        'signupform': signupform,
        
    })

def logout_user(request):
    logout(request)
    return redirect('/')

@login_required
def profile(request):
    return render(request, 'templates/user/profile.html')

Note_port/notes/items/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth.decorators import login_required 
from . import models 
from . import forms 


@login_required 
def view_notes(request):
    user_notes = models.Notes.objects.filter(user = request.user)
    return render(request, 'templates/user/allNotes.html', {
        'user_notes':user_notes,
    })

@login_required
def new_notes(request):
    if request.method == 'POST':
        new_note_form = forms.new_note(request.POST)

        if new_note_form.is_valid:
            new_note = new_note_form.save(commit= False)
            new_note.user = request.user
            new_note.save()
            return redirect('/mynotes')
        
    new_note_form = forms.new_note()
    return render(request, 'templates/items/create.html', {
        'new_note':new_note_form, 
    })

def notes_details(request, id):
    note = get_object_or_404(models.Notes, pk =id)
    return render(request, 'templates/user/viewNotes.html',{
        'note':note,
    })

Note_port/notes/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %} | SWAE Notes </title>
</head>
<header>
    <nav>
        {% if request.user.is_authenticated %}
            <a href="{% url 'core:index' %}">Home</a>
            <a href="{% url 'core:profile' %}">Profile</a>
            <a href="{% url 'items:user_notes' %}">My notes</a>
            <a href="{% url 'core:logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'core:index' %}">Home</a>
            <a href="{% url 'core:login' %}">Login</a>
            <a href="{% url 'core:signup' %}">Signup</a>
        {% endif %}

    
    </nav>
</header>
<body>
    {% block content %}

    {% endblock %}
</body>
</html>

Note_port/notes/templates/core/index.html
{% extends 'templates/base.html' %}

{% block title %}Home {% endblock %}

{% block content %}

    {% if request.user.is_authenticated %}
    <h3>Welcome, {{request.user}} </h3>
    <a href="{% url 'items:user_notes' %}">View My Notes </a>
    {% else %}
        <div>
            <h3>Home</h3>
            <small>Kindly login <a href="{% url 'core:login' %}">here</a> to view your notes <br>Or <a href="{% url 'core:signup' %}">signup</a> to start creating your notes </small>
        </div>
    {% endif %}

{% endblock %}

Note_port/notes/templates/items/create.html
{% extends 'templates/base.html' %}

{% block title %}New Note {% endblock %}

{% block content %}
    <h3>New Note</h3>
    <form method="post">
        {% csrf_token %}

        {{new_note.as_p}}
        <input type="submit" value="Create">
    </form>
{% endblock %}

Note_port/notes/templates/user/allNotes.html
{% extends 'templates/base.html' %}

{% block title %}My Notes {% endblock %}

{% block content %}
    <div>
        <h3>My Notes</h3>
        <a href="{% url 'items:create' %}">Add Notes</a>

            {% for notes in user_notes %}
                <a href="{% url 'items:details' notes.id %}">
                    <p>{{notes.title}}</p>
                    <small>{{notes.content}}</small>
                </a>
            {% endfor %}
       
    </div>
{% endblock %}

Note_port/notes/templates/user/profile.html
{% extends 'templates/base.html' %}

{% block title %}Home {% endblock %}

{% block content %}

    {% if request.user.is_authenticated %}
        <div>
            <h3>Welcome {{request.user}}</h3>
        </div>
    {% else %}
        <h3>You're not logged in</h3>
        <small>Kindly login <a href="{% url 'core:login' %}">here</a></small>
    {% endif %}

{% endblock %}

Note_port/notes/templates/user/viewNotes.html
{% extends 'templates/base.html' %}

{% block title %}{{note.title}} {% endblock %}

{% block content %}
    <h3>{{note.title}}</h3>
    <p>{{note.content}}</p>
{% endblock %}